# Generated by Django 5.2.5 on 2025-08-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['issue_date']},
        ),
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['reading_date']},
        ),
    ]
